### PR TITLE
fix "ExceptionThrowed" event can't  post BUG

### PR DESCRIPTION
**Pull request by SocialSisterYi**

### CODE REVIEW

**Comment by BlueGlassBlock** [comment]
May cause performance drop?

**Comment by SocialSisterYi** [comment]
> May cause performance drop?

NO, but the Exception throw in the Event can't be listened

**Comment by BlueGlassBlock** [comment]
That is a problem indeed.

Or making all the options configurable is a better solution, I think.

**Review by BlueGlassBlock — APPROVED** [review]

**Comment by GreyElaina** [comment]
我到底是什么时候写的elif。。。我记得应该是写的if

**Pull request merged**
